on: 
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 4'

env:
  AGNOSTIC_API_KEY: ${{ secrets.AGNOSTIC_API_KEY }}
  RPC_URL: ${{ secrets.RPC_URL }}
  BSC_RPC_URL: ${{ secrets.BSC_RPC_URL }}

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run start
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4